name: musical-palm-tree
runtime: nodejs
description: AWS Lambda deployment for Musical Palm Tree QR Code Creator
template:
  config:
    aws:region:
      description: The AWS region to deploy to
      default: us-east-1
    appName:
      description: The name of the application
      default: musical-palm-tree
    environment:
      description: The deployment environment
      default: dev
